var day = "Monday";

switch (day) {
  case "Monday":
    var jenis = "weekday";
    break;

  case "Tuesday":
    var jenis = "weekday";
    break;

  case "Wednesday":
    var jenis = "weekday";
    break;

  case "Thursday":
    var jenis = "weekday";
    break;

  case "Friday":
    var jenis = "weekday";
    break;

  case "Saturday":
    var jenis = "weekend";
    break;

  case "Sunday":
    var jenis = "Weekend";
    break;

  default:
    "nama hari tidak valid";
    break;
}
console.log(jenis);
